# export keys in your .profile file
development: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || '4fa9125322603ccc43b2a85018060aa8cb86990e4bb9ecfa19535ec0f5186c888df20d454edcf6eb2e8a8c0e17a195ff1121092f44a5fedfdbf58e9d934e812b' %>
  # sending emails
  mandrill_api_key: <%= ENV['MANDRILL_API_KEY'] %>
  mail_interceptor_email: <%= ENV['MAIL_INTERCEPTOR_EMAIL'] %>

test: *default
production: *default

