# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daf683451d73c9171d7b915517076b6180beb5d73bc40f59b0810094fa82eb55d10eda9f2afedd3ca4317e7b05788d2a1e4141b38611cf506f949e495aba1759

test:
  secret_key_base: dd95a1c5bd4328346fe373cc81bfc442138fbba122b0e6f4676080c08105add53e31bcd8a3318202030c653dd4d8f33eb1366d192c7e35abb8ab3a25b77519e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
